(cl:defpackage arbotix_msgs-srv
  (:use )
  (:export
   "SETSPEED"
   "<SETSPEED-REQUEST>"
   "SETSPEED-REQUEST"
   "<SETSPEED-RESPONSE>"
   "SETSPEED-RESPONSE"
   "RELAX"
   "<RELAX-REQUEST>"
   "RELAX-REQUEST"
   "<RELAX-RESPONSE>"
   "RELAX-RESPONSE"
   "ENABLE"
   "<ENABLE-REQUEST>"
   "ENABLE-REQUEST"
   "<ENABLE-RESPONSE>"
   "ENABLE-RESPONSE"
   "SETUPCHANNEL"
   "<SETUPCHANNEL-REQUEST>"
   "SETUPCHANNEL-REQUEST"
   "<SETUPCHANNEL-RESPONSE>"
   "SETUPCHANNEL-RESPONSE"
  ))

