set(_CATKIN_CURRENT_PACKAGE "ros_hello_erle")
set(ros_hello_erle_VERSION "0.1.0")
set(ros_hello_erle_MAINTAINER "Stefano <you@yourdomain.tld>")
set(ros_hello_erle_PACKAGE_FORMAT "1")
set(ros_hello_erle_BUILD_DEPENDS "roscpp" "rospy" "std_msgs")
set(ros_hello_erle_BUILD_EXPORT_DEPENDS "roscpp" "rospy" "std_msgs")
set(ros_hello_erle_BUILDTOOL_DEPENDS "catkin")
set(ros_hello_erle_BUILDTOOL_EXPORT_DEPENDS )
set(ros_hello_erle_EXEC_DEPENDS "roscpp" "rospy" "std_msgs")
set(ros_hello_erle_RUN_DEPENDS "roscpp" "rospy" "std_msgs")
set(ros_hello_erle_TEST_DEPENDS )
set(ros_hello_erle_DOC_DEPENDS )
set(ros_hello_erle_DEPRECATED "")